name = "PlasmoPlots"
uuid = "a21664a3-f668-4e98-8a13-7892286ec16a"
authors = ["Jordan Jalving <jhjalving@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"
Plasmo = "d3f7391f-f14a-50cc-bbe4-76a32d1bad3c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
LightGraphs = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
